services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '5002:5002'
        environment:
            NODE_ENV: production
            PORT: 5002
