apiVersion: v1
kind: Service
metadata:
  name: streamify-backend
spec:
  selector:
    app: streamify-backend
  ports:
  - protocol: TCP
    port: 5000  # BACKEND_PORT
    targetPort: 5000  # BACKEND_PORT
  type: ClusterIP